package apps;
import javax.swing.*;


/**
 *
 * @author Hidee
 */
public class Home extends javax.swing.JFrame {

    private boolean o=false,norm=false;
    /**
     * Creates new form Home
     */
    public Home() {
        initComponents();       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        label1 = new java.awt.Label();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jButton2 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jMenuItem1 = new javax.swing.JMenuItem();
        panel1 = new java.awt.Panel();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        val = new javax.swing.JTextField();
        converted = new javax.swing.JComboBox<>();
        convert1 = new javax.swing.JComboBox<>();
        converter = new javax.swing.JButton();
        jToggleButton1 = new javax.swing.JToggleButton();
        jButton3 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        diss = new javax.swing.JTextArea();
        other = new javax.swing.JComboBox<>();
        otherf = new javax.swing.JTextField();
        jMenuBar1 = new javax.swing.JMenuBar();

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        label1.setText("label1");

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        jButton2.setText("M");

        jTextField1.setBackground(new java.awt.Color(102, 0, 0));
        jTextField1.setFont(new java.awt.Font("Tempus Sans ITC", 3, 14)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(153, 51, 255));
        jTextField1.setText("EXIT");
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panel1.setBackground(new java.awt.Color(0, 0, 0));
        panel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        panel1.setFont(new java.awt.Font("Dialog", 3, 18)); // NOI18N
        panel1.setForeground(new java.awt.Color(204, 204, 255));

        jLabel1.setBackground(new java.awt.Color(153, 0, 153));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText(" DISTANCE CONVERSION");

        javax.swing.GroupLayout panel1Layout = new javax.swing.GroupLayout(panel1);
        panel1.setLayout(panel1Layout);
        panel1Layout.setHorizontalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addGap(86, 86, 86)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panel1Layout.setVerticalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
        );

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));
        jPanel1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(204, 0, 0)));
        jPanel1.setForeground(new java.awt.Color(51, 51, 51));

        val.setEditable(false);
        val.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                valMouseClicked(evt);
            }
        });
        val.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                valInputMethodTextChanged(evt);
            }
        });
        val.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                valActionPerformed(evt);
            }
        });

        converted.setBackground(new java.awt.Color(204, 204, 204));
        converted.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        converted.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "millimeter", "centimeter", "decimeter", "meter", "decameter", "hectometer", "kilometer", "feet", "yard", "mile", "inch", "furlong" }));
        converted.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                convertedActionPerformed(evt);
            }
        });

        convert1.setBackground(converted.getBackground());
        convert1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        convert1.setForeground(converted.getForeground());
        convert1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "millimeter", "centimeter", "decimeter", "meter", "decameter", "hectometer", "kilometer" }));
        convert1.setSelectedIndex(-1);
        convert1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                convert1ActionPerformed(evt);
            }
        });

        converter.setBackground(new java.awt.Color(102, 102, 102));
        converter.setFont(new java.awt.Font("RomanC", 1, 14)); // NOI18N
        converter.setForeground(new java.awt.Color(255, 255, 255));
        converter.setText("CONVERT");
        converter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                converterActionPerformed(evt);
            }
        });

        jToggleButton1.setBackground(new java.awt.Color(51, 51, 51));
        jToggleButton1.setFont(new java.awt.Font("RomanC", 2, 12)); // NOI18N
        jToggleButton1.setForeground(new java.awt.Color(204, 204, 204));
        jToggleButton1.setText("CLEAR");
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Tempus Sans ITC", 3, 11)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 153, 153));
        jButton3.setText("<<<");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        diss.setEditable(false);
        diss.setColumns(20);
        diss.setFont(new java.awt.Font("Myanmar Text", 1, 13)); // NOI18N
        diss.setRows(5);
        jScrollPane2.setViewportView(diss);

        other.setBackground(converted.getBackground());
        other.setFont(convert1.getFont());
        other.setForeground(converted.getForeground());
        other.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "feet", "yard", "mile", "inch", "furlong" }));
        other.setSelectedIndex(-1);
        other.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                otherActionPerformed(evt);
            }
        });

        otherf.setEditable(false);
        otherf.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                otherfMouseClicked(evt);
            }
        });
        otherf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                otherfActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(val, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(otherf, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(convert1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50)
                        .addComponent(other, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(86, 86, 86)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(131, 131, 131)
                        .addComponent(converted, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(113, 113, 113)
                        .addComponent(converter, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(154, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(140, 140, 140)
                .addComponent(jToggleButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton3))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(convert1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(other, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(val, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(otherf, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(converter, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(converted, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(jToggleButton1)
                .addGap(21, 21, 21))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButton3))
        );

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
   
    
    private void convert1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_convert1ActionPerformed
        try{
            if(convert1.getSelectedIndex()==-1)
                val.setEditable(false);
            else
                val.setEditable(true);

            Double stat=Double.parseDouble(val.getText());
            if(stat!=0.000000000000){
             converter.doClick();
            }
        }catch(Exception e){
        }
    }//GEN-LAST:event_convert1ActionPerformed

    private void valActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_valActionPerformed
        
    }//GEN-LAST:event_valActionPerformed

    private void converterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_converterActionPerformed
        try{
            double no=Double.parseDouble(val.getText());
             int from = convert1.getSelectedIndex();
             int to = converted.getSelectedIndex();
             String Ans_unit = (String)converted.getSelectedItem();
             if(norm==true){ 
             String from1=(String)other.getSelectedItem();
             otherf.setText(String.format("%.4f",toAlt(from1,no/(Math.pow(10,3-from)))));
             if(to<7){
                 no=(no)/(Math.pow(10, to-from));
              diss.setText(String.format("%.3f",(no))+Ans_unit);
             }
             else{
                 String unit = (String)converted.getSelectedItem();
                   no=(no)/(Math.pow(10,3-from));
                 diss.setText(String.format("%.5f%s",toAlt(unit,no),Ans_unit));
             }

         /*   int way =convert1.getSelectedIndex();
             int destiny = coverted.getSelectedIndex();
             double no=0.00;  
                 destiny = destiny-way;
              no=Double.parseDouble(val.getText());
              no=(no)/(Math.pow(10, destiny));
              String unit =(String) coverted.getSelectedItem();
                 diss.setText(String.format("%f",(no))+"");
              variant();
           */   
          }
          else if(o==true){
              no=Double.parseDouble(otherf.getText());
              String unit =(String)other.getSelectedItem();
              double x=(no*(Math.pow(10,3-from)));
              val.setText(String.format("%.3f",toMeter(unit,x)));
              if(to<7){
              from=3-from;
              diss.setText(String.format("%.3f%s",toMeter(unit,(no*(Math.pow(10,3-to)))),Ans_unit));
              }
              else{
                   String unit2 = (String)converted.getSelectedItem();
                   no=toMeter(unit,(no));
                 diss.setText(String.format("%.3f%s",toAlt(unit2,no),Ans_unit));
              }
          }
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,"error");
        }
    }//GEN-LAST:event_converterActionPerformed
    
    public double toMeter(String unit,double from){
        double no=0.00;
        switch(unit){
            case "feet":
                no=(from*0.305);
                break;
            case "yard":
                no=from*0.9149;
                break;
            case "mile":
                no=(from*1612.9);
                break;
            case "inch":
                no=(from*0.0254);
                break;
            case "furlong":
                no=(from*201.61);
                break;
        }
        return no;
        }
    
    
    public double toAlt(String unit,double no){
        //no will have to be converted to meter first
        //and that is what will be in the constructor
        switch(unit){
            case "feet":
                no=(no*3.28);
                break;
            case "yard":
                no=no*1.093;
                break;
            case "mile":
                no=(no*0.00062);
                break;
            case "inch":
                no=(no*39.37);
                break;
            case "furlong":
                no=(no*0.00496);
                break;
        }
        return no;
    }
            
    
    public void variantC(String to){
        double no = Double.parseDouble(otherf.getText());
        double also = (int)convert1.getSelectedIndex();
        double from =(int) converted.getSelectedIndex();
        double trial =(int) converted.getSelectedIndex();
        from=3-from;
        also=3-also;
        
        switch(to){
            case "feet":
                from=(no)*(Math.pow(10,from));
                if(trial==7)
                    diss.setText(String.format("%f",(no*0.305*39.3)));
                else
                diss.setText(String.format("%.4f",(from*0.305))+"");
                    also=(no)*(Math.pow(10,also));
                    val.setText(String.format("%.4f",(also*0.305))+"");
                break;
            case "yard":
                from=(no)*(Math.pow(10,from));
                diss.setText(String.format("%.4f",(from*0.9149))+"");
                also=(no)*(Math.pow(10,also));
                val.setText(String.format("%.4f",(also*0.9149))+"");
                break;
            case "mile":
                from=(no)*(Math.pow(10,from));
                diss.setText(String.format("%.4f",(from*1612.9))+"");
                also=(no)*(Math.pow(10,also));
                val.setText(String.format("%.4f",(also*1612.9))+"");
                break;
            case "inch":
                from=(no)*(Math.pow(10,from));
                diss.setText(String.format("%.4f",(from*0.0254))+"");
                also=(no)*(Math.pow(10,also));
                val.setText(String.format("%.4f",(also*0.0254))+"");
                break;
            case "furlong":
                from=(no)*(Math.pow(10,from));
                diss.setText(String.format("%.4f",(from*201.61))+"");
                also=(no)*(Math.pow(10,also));
                val.setText(String.format("%.4f",(also*201.61))+"");
                break;
        }
    }
    
    public void variant(){
        double no = Double.parseDouble(val.getText());
        int from = convert1.getSelectedIndex();
        from=3-from;
        String to = (String)other.getSelectedItem();
        switch(to){
            case "feet":
                no=(no)/(Math.pow(10,from));
                otherf.setText(String.format("%.4f",(no*3.28))+"");
                break;
            case "yard":
                no=(no)/(Math.pow(10,from));
                otherf.setText(String.format("%.4f",(no*1.093))+"");
                break;
            case "mile":
                no=(no)/(Math.pow(10,from));
                otherf.setText(String.format("%.6f",(no*0.00062))+"");
                break;
            case "inch":
                no=(no)/(Math.pow(10,from));
                otherf.setText(String.format("%.4f",(no*39.3))+"");
                break;
            case "furlong":
                no=(no)/(Math.pow(10,from));
                otherf.setText(String.format("%.4f",(no*0.00496))+"");
                break;
        }
    }
    private void convertedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_convertedActionPerformed
        try{
            Double stat=Double.parseDouble(val.getText());
            if(stat!=0.000000000000){
                converter.doClick();
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,"error");
        }
    }//GEN-LAST:event_convertedActionPerformed

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
       diss.setText("");
       val.setText("");
       otherf.setText("");
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
       
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
          kkk test = new kkk();
        test.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void otherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_otherActionPerformed
        try{
            if(other.getSelectedIndex()==-1)
                otherf.setEditable(false);
            else
                otherf.setEditable(true);

            Double stat=Double.parseDouble(otherf.getText());
            if(stat!=0.000000000000){
                converter.doClick();
            }
        }catch(Exception e){
        }
    }//GEN-LAST:event_otherActionPerformed

    private void otherfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_otherfActionPerformed

    }//GEN-LAST:event_otherfActionPerformed

    private void valInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_valInputMethodTextChanged
        
    }//GEN-LAST:event_valInputMethodTextChanged

    private void otherfMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_otherfMouseClicked
        o = true;
        norm=false;
    }//GEN-LAST:event_otherfMouseClicked

    private void valMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_valMouseClicked
        norm = true;
        o = false;
    }//GEN-LAST:event_valMouseClicked

    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> convert1;
    private javax.swing.JComboBox<String> converted;
    private javax.swing.JButton converter;
    private javax.swing.JTextArea diss;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JList<String> jList1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JToggleButton jToggleButton1;
    private java.awt.Label label1;
    private javax.swing.JComboBox<String> other;
    private javax.swing.JTextField otherf;
    private java.awt.Panel panel1;
    private javax.swing.JTextField val;
    // End of variables declaration//GEN-END:variables
}
