
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Hidee
 */
public class matMult extends javax.swing.JFrame {

   private double matrix4[][] = new double[4][4];
   public int dipp,n=0;
    public matMult() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fc = new javax.swing.JFileChooser();
        pop = new javax.swing.JPopupMenu();
        jLabel1 = new javax.swing.JLabel();
        m00 = new javax.swing.JTextField();
        m02 = new javax.swing.JTextField();
        m03 = new javax.swing.JTextField();
        m13 = new javax.swing.JTextField();
        m12 = new javax.swing.JTextField();
        m10 = new javax.swing.JTextField();
        m01 = new javax.swing.JTextField();
        m11 = new javax.swing.JTextField();
        m20 = new javax.swing.JTextField();
        m21 = new javax.swing.JTextField();
        m22 = new javax.swing.JTextField();
        m23 = new javax.swing.JTextField();
        m30 = new javax.swing.JTextField();
        m31 = new javax.swing.JTextField();
        m32 = new javax.swing.JTextField();
        m33 = new javax.swing.JTextField();
        determinant = new javax.swing.JButton();
        result = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText(" MATRIX DETERMINANT");

        m00.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                m00MouseExited(evt);
            }
        });
        m00.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                m00InputMethodTextChanged(evt);
            }
        });
        m00.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                m00ActionPerformed(evt);
            }
        });
        m00.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                m00KeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                m00KeyTyped(evt);
            }
        });

        m02.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                m02MouseExited(evt);
            }
        });

        m03.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                m03MouseExited(evt);
            }
        });
        m03.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                m03ActionPerformed(evt);
            }
        });

        m13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                m13MouseExited(evt);
            }
        });
        m13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                m13ActionPerformed(evt);
            }
        });

        m12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                m12MouseExited(evt);
            }
        });
        m12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                m12ActionPerformed(evt);
            }
        });

        m10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                m10MouseExited(evt);
            }
        });

        m01.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                m01MouseExited(evt);
            }
        });
        m01.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                m01InputMethodTextChanged(evt);
            }
        });
        m01.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                m01ActionPerformed(evt);
            }
        });

        m11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                m11MouseExited(evt);
            }
        });
        m11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                m11ActionPerformed(evt);
            }
        });

        m20.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                m20MouseExited(evt);
            }
        });
        m20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                m20ActionPerformed(evt);
            }
        });

        m21.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                m21MouseExited(evt);
            }
        });
        m21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                m21ActionPerformed(evt);
            }
        });

        m22.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                m22MouseExited(evt);
            }
        });
        m22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                m22ActionPerformed(evt);
            }
        });

        m23.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                m23MouseExited(evt);
            }
        });
        m23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                m23ActionPerformed(evt);
            }
        });

        m30.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                m30MouseExited(evt);
            }
        });
        m30.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                m30ActionPerformed(evt);
            }
        });

        m31.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                m31MouseExited(evt);
            }
        });
        m31.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                m31ActionPerformed(evt);
            }
        });

        m32.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                m32MouseExited(evt);
            }
        });
        m32.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                m32ActionPerformed(evt);
            }
        });

        m33.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                m33MouseExited(evt);
            }
        });
        m33.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                m33ActionPerformed(evt);
            }
        });

        determinant.setText("CALCULATE");
        determinant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                determinantActionPerformed(evt);
            }
        });

        result.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(m10, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(m11, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(9, 9, 9))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(m00, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(m01, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(10, 10, 10)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(m02)
                                    .addComponent(m12, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(m13, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(m03, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(m20, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(m21, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(m22, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(m23, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(m30, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(m31, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(m32, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(m33))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(96, 96, 96)
                        .addComponent(determinant))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(result, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(164, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(m00, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(m02)
                    .addComponent(m03, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(m01, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(m13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(m12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(m10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(m11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(m20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(m21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(m22)
                    .addComponent(m23, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(m30, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(m31, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(m32, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(m33, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(determinant)
                .addGap(18, 18, 18)
                .addComponent(result, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void m21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_m21ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_m21ActionPerformed

    private void m22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_m22ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_m22ActionPerformed

    private void m23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_m23ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_m23ActionPerformed

    private void m30ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_m30ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_m30ActionPerformed

    private void m31ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_m31ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_m31ActionPerformed

    private void m32ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_m32ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_m32ActionPerformed

    private void m33ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_m33ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_m33ActionPerformed

    private void m03ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_m03ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_m03ActionPerformed

    private void m00ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_m00ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_m00ActionPerformed

    private void m11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_m11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_m11ActionPerformed

    private void m12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_m12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_m12ActionPerformed

    private void m20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_m20ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_m20ActionPerformed

    private void m01InputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_m01InputMethodTextChanged
       
    }//GEN-LAST:event_m01InputMethodTextChanged

    private void m00InputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_m00InputMethodTextChanged
         matrix4[0][0]=Double.parseDouble(m00.getText());
    }//GEN-LAST:event_m00InputMethodTextChanged

    private void determinantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_determinantActionPerformed
        pop.show(pop, 30, 13);
        double det = fourM(matrix4);
       result.setText(String.format("Determinant is %.3f",det));
    }//GEN-LAST:event_determinantActionPerformed

    private void m00KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_m00KeyTyped
        
    }//GEN-LAST:event_m00KeyTyped

    private void m00KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_m00KeyPressed
       
    }//GEN-LAST:event_m00KeyPressed

    private void m00MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_m00MouseExited
        matrix4[0][0]=Double.parseDouble(m00.getText());
    }//GEN-LAST:event_m00MouseExited

    private void m01MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_m01MouseExited
        matrix4[0][1]=Double.parseDouble(m01.getText());
    }//GEN-LAST:event_m01MouseExited

    private void m02MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_m02MouseExited
        matrix4[0][2]=Double.parseDouble(m02.getText());
    }//GEN-LAST:event_m02MouseExited

    private void m03MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_m03MouseExited
        matrix4[0][3]=Double.parseDouble(m03.getText());
    }//GEN-LAST:event_m03MouseExited

    private void m10MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_m10MouseExited
        matrix4[1][0]=Double.parseDouble(m10.getText());
    }//GEN-LAST:event_m10MouseExited

    private void m11MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_m11MouseExited
        matrix4[1][1]=Double.parseDouble(m11.getText());
    }//GEN-LAST:event_m11MouseExited

    private void m12MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_m12MouseExited
        matrix4[1][2]=Double.parseDouble(m12.getText());
    }//GEN-LAST:event_m12MouseExited

    private void m13MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_m13MouseExited
       matrix4[1][3]=Double.parseDouble(m13.getText());
    }//GEN-LAST:event_m13MouseExited

    private void m20MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_m20MouseExited
        matrix4[2][0]=Double.parseDouble(m20.getText());
    }//GEN-LAST:event_m20MouseExited

    private void m21MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_m21MouseExited
        matrix4[2][1]=Double.parseDouble(m21.getText());
    }//GEN-LAST:event_m21MouseExited

    private void m22MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_m22MouseExited
        matrix4[2][2]=Double.parseDouble(m22.getText());
    }//GEN-LAST:event_m22MouseExited

    private void m23MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_m23MouseExited
        matrix4[2][3]=Double.parseDouble(m23.getText());
    }//GEN-LAST:event_m23MouseExited

    private void m30MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_m30MouseExited
        matrix4[3][0]=Double.parseDouble(m30.getText());
    }//GEN-LAST:event_m30MouseExited

    private void m31MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_m31MouseExited
        matrix4[3][1]=Double.parseDouble(m31.getText());
    }//GEN-LAST:event_m31MouseExited

    private void m32MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_m32MouseExited
        matrix4[3][2]=Double.parseDouble(m32.getText());
    }//GEN-LAST:event_m32MouseExited

    private void m33MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_m33MouseExited
        matrix4[3][3]=Double.parseDouble(m33.getText());
    }//GEN-LAST:event_m33MouseExited

    private void m01ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_m01ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_m01ActionPerformed

    private void m13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_m13ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_m13ActionPerformed

     public double name(double[][] x)
     {    
        double a = x[0][0]*((x[1][1]*x[2][2])-(x[1][2]*x[2][1]));
        double b = -x[0][1]*((x[1][0]*x[2][2])-(x[1][2]*x[2][0]));
        double c = x[0][2]*((x[1][0]*x[2][1])-(x[1][1]*x[2][0]));
        double mat=a+b+c;
        System.out.println("3*3_"+(n++)+"is "+mat);
        return mat;
    }
    
     public double fourM(double[][] x){
        double v[][]= new double[3][3];
        double i1=0.0;
        int k=0,l=0;
        for(int u=0;u<4;u++){
            k=0;
            for(int j=1;j<4;j++,k++){
           l=0;
                for(int i=0;i<4;i++){ 
                if(j!=0&&i!=u)
                    v[k][l++]=x[j][i];
            }
        }
            System.out.println("Matrix "+n);
            for(int i=0;i<v.length;i++){
                for(int j=0;j<3;j++)
                    System.out.print(v[i][j]+"  ");
                System.out.println();
        }
            if(u%2==0)
        i1 += x[0][u]*name(v);
            else
               i1 += -x[0][u]*name(v);
        }
//                JOptionPane.showMessageDialog(null,i1);
        return i1;

    }
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(matMult.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(matMult.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(matMult.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(matMult.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new matMult().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton determinant;
    private javax.swing.JFileChooser fc;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField m00;
    private javax.swing.JTextField m01;
    private javax.swing.JTextField m02;
    private javax.swing.JTextField m03;
    private javax.swing.JTextField m10;
    private javax.swing.JTextField m11;
    private javax.swing.JTextField m12;
    private javax.swing.JTextField m13;
    private javax.swing.JTextField m20;
    private javax.swing.JTextField m21;
    private javax.swing.JTextField m22;
    private javax.swing.JTextField m23;
    private javax.swing.JTextField m30;
    private javax.swing.JTextField m31;
    private javax.swing.JTextField m32;
    private javax.swing.JTextField m33;
    private javax.swing.JPopupMenu pop;
    private javax.swing.JTextField result;
    // End of variables declaration//GEN-END:variables
}
