package com.mycompany.IBMworks;

import static com.codename1.ui.CN.*;
import com.codename1.components.SpanLabel;
import com.codename1.io.Log;
import com.codename1.ui.Button;
import com.codename1.ui.Dialog;
import com.codename1.ui.Form;
import com.codename1.ui.plaf.UIManager;
import com.codename1.ui.util.Resources;
import com.codename1.ui.Container;
import com.codename1.ui.FontImage;
import com.codename1.ui.PickerComponent;
import com.codename1.ui.TextComponent;
import com.codename1.ui.Toolbar;
import com.codename1.ui.layouts.BorderLayout;
import com.codename1.ui.layouts.BoxLayout;
import com.codename1.ui.layouts.TextModeLayout;
import com.codename1.ui.validation.GroupConstraint;
import com.codename1.ui.validation.LengthConstraint;
import com.codename1.ui.validation.RegexConstraint;
import com.codename1.ui.validation.Validator;
import com.codename1.io.NetworkEvent;
import static com.mycompany.IBMworks.Aptitude.sectNo;

/**
 * This file was generated by <a href="https://www.codenameone.com/">Codename One</a> for the purpose 
 * of building native mobile applications using Java.
 */
public class MyApplication {

    private Form current;
    private Resources theme;

    private Form home;

    public void init(Object context) {
        // use two network threads instead of one
        updateNetworkThreadCount(2);

        theme = UIManager.initFirstTheme("/theme");

        // Enable Toolbar on all Forms by default
        Toolbar.setGlobalToolbar(true);

        // Pro only feature
        Log.bindCrashProtection(true);

        addNetworkErrorListener(err -> {
            // prevent the event from propagating
            err.consume();
            if(err.getError() != null) {
                Log.e(err.getError());
            }
            Log.sendLogAsync();
            Dialog.show("Connection Error", "There was a networking error in the connection to " + err.getConnectionRequest().getUrl(), "OK", null);
        });        
    }

    public void start() {
        if (current != null) {
            current.show();
            return;
        }

        TextModeLayout tm = new TextModeLayout(4, 2);
        home = new Form("LOGIN ", new BorderLayout());
        
        Container content = new Container(tm);
//        content.add(tm.createConstraint().horizontalSpan(2), new SpanLabel("This form adapts to OS differences in iOS and Android"));
        
        TextComponent name = new TextComponent().labelAndHint("Name");
        content.add(tm.createConstraint().horizontalSpan(2), name);

//        TextComponent bio = new TextComponent().labelAndHint("Bio").multiline(true).rows(3);
//        content.add(tm.createConstraint().horizontalSpan(2), bio);
//        
//        bio = new TextComponent().labelAndHint("Bio").multiline(true).rows(3);
//        content.add(tm.createConstraint().horizontalSpan(2), bio);
//
        PickerComponent gender = PickerComponent.createStrings("Male", "Female").label("Gender");
        content.add(gender);
//
//        PickerComponent dateOfBirth = PickerComponent.createDate(null).label("Birthday");
//        content.add(dateOfBirth);
        
        content.setScrollableY(true);
                
        Button submit = new Button("Submit");
        FontImage.setMaterialIcon(submit, FontImage.MATERIAL_DONE);
        submit.addActionListener(e -> {
            showOKForm(name.getField().getText(),gender.getPicker().getSelectedString());
        });
        
        home.add(NORTH, content);
        home.add(SOUTH, submit);
        
        Validator val = new Validator();
        val.setShowErrorMessageForFocusedComponent(true);
        val.addConstraint(name, 
                new GroupConstraint(
                        new LengthConstraint(2), 
                        new RegexConstraint("^([a-zA-Z ]*)$", "Please only use latin characters for name"))).
                addSubmitButtons(submit);
        
        
        home.show();
    }

    private void showOKForm(String name,String gender) {
//        System.out.println(name+gender);
        Aptitude.userName = name;
        Aptitude.sex = gender;
        if(gender==null){
            Dialog.setDefaultBlurBackgroundRadius(DENSITY_MEDIUM);
            Dialog.show("Error", "Please fill in gender", "OK", null);
        }
        else{
//            Form f = new Form("Thanks", BoxLayout.y());
            instrPage test = new instrPage();
            instrPage pg = new instrPage();
//            f.add(new SpanLabel("Thanks " + name + " for your submission. You can press the back arrow and try again"));
            pg.getToolbar().setBackCommand("", e -> home.showBack());
            
            
            pg.show();
        }
        
    }
    
    public static String[][] toTable(){
        Aptitude.setQuestion();
        String quest[][] = new String[8][2];
        for(int i=0;i<8;i++){
                quest[i][0]=Aptitude.section[sectNo].getQuestions()[i];
                quest[i][1]=null;
        }
        return quest;
    }
    
    public void stop() {
        current = getCurrentForm();
        if(current instanceof Dialog) {
            ((Dialog)current).dispose();
            current = getCurrentForm();
        }
    }

    public void destroy() {
    }

}




class Aptitude {
static String userName;
static String sex;
static Assessment section[] = new Assessment[7];
static int sectNo=0;
static int char1=-1,char2=-1;
static String[] character = {"SHAPER","CO-ORDINATOR","PLANTER","RESOURCE INVESTIGATOR","MONITOR EVALUATOR","IMPLEMENTER","TEAMWORKER","FINISHER"};
static int[] charTotal = new int[8];

    static void resetUser() {
        userName=null;
        sex=null;
        sectNo=0;
        char1=-1;
        char2=-1;
        charTotal = new int[8];
        resetSection();
    }
    /**
     * @param args the command line arguments
     */

     public Aptitude(){

     }
     
     public static void resetSection(){
         section = new Assessment[7];
         setQuestion();
     }
         
     
     public static void setQuestion(){
         section[0] = new Assessment("I can be relied upon to see that work that needs to be done is organised",
                "I pick up slips and omissions that others fail to notice",
                "I react strongly when meetings look like losing track of the main objective",
                "I produce original suggestions",
                "I analyse other people's ideas objectively, for both merits and failings",							
                "I am keen to find out the latest ideas and developments",							
                "I have an aptitude for organising people",							
                "I am always ready to support good suggestions that help to resove a problem"							
                );
        section[1]= new Assessment("I like to have a strong influence on decisions",
                "I feel in my elements where work requires a high degree of attention and concentration",
                "I am concerned to help colleagues with their problems",
                "I like to make critical discrimination between alternatives",
                "I tend to have a creative approach to problem solving",							
                "I enjoy reconciliation of different points of view",							
                "I am more interested in practicalities than in new ideas",							
                "I particularly enjoy exploring different views and techniques"							
                );
        section[2]= new Assessment("I keep a watching eye on areas where difficulty may arise",							
                "I explore ideas that may have a wider application than in the immediate task",							
                "I like to weigh up and evaluate a range of suggestions thoroughly before choosing",							
                "I can co-ordinate and use productively other people's abilities and talents",							
                "I maintain a steady systematic approach, whatever the pressure",							
                "I often produce a new approach to a long continuing problem",							
                "I am ready to make my personal views known in a forceful way if necessary",							
                "I am ready to help whenever I can"							
                );
        section[3]= new Assessment("I am keen to see there is nothing vague about my task and objectives",							
                "I am not reluctant to emphasize my own point of view on meetings",							
                "I can work with all sorts of people provided that they have got something worthwhile to contribute",							
                "I like following up interesting ideas and/or people",							
                "I can usually find the argument to refute unsound proposition",							
                "I tend to see patterns where others see unconnected items",							
                "Being busy gives me real satisfaction",							
                "I have a quiet interest in getting to know people better"														
                );
        section[4]= new Assessment("I often find my imagination frustrated by working in a group",							
                "I find my personal skill particularly appropriate in  achieving agreement",							
                "My feelings seldom interfere with my judgments",							
                "I strive to build up an effective structure",							
                "I can work with people who vary widely in their personal qualities and outlooks",							
                "I feel it is sometimes worth incurring some temporary unpopularity if one is to succeed in  getting one's views across in a group",							
                "I usually know someone whose specialist knowledge is particularly apt",							
                "I seem to develop a natural sense of urgency"																			
                );
        section[5]= new Assessment("I start to look around for possible ideas and openings",							
                "I am concerned to finish and perfect current work before I start a new one",							
                "I approach the problem in a carefully analytical way",							
                "I am able to assert myself to get other people involved if necessary",							
                "I am able to take an independent and innovative look at most situations",							
                "I am happy to take the lead when action is required",							
                "I can respond positively to my colleagues and their initiatives",							
                "I find it hard to give in to a job where goals are not clearly defined"																										
                );
        section[6]= new Assessment("I think I have a talent for sorting out the concrete steps that need to be taken, given a broad brief",							
                "My considered judgments may take time but is usually near the mark",							
                "A broad range of personal contacts is important to my style of working",							
                "I have an eye for getting the details right",							
                "I try to make my mark in group meetings",							
                "I can see how ideas and techniques can be used in relationships",							
                "I see both sides of a problem and take a decision acceptable to all",							
                "I get on well with others and work hard for the team"																										
                );

     }

    
    public void setUserName(String name){
        userName = name;
    }
    
    static String getUserName(){
        return userName;
    }
    
    public void setSex(String Sex){
        sex = Sex;
    }
    
    static String getSex(){
        return sex;
    }
    
    static String getTitle(){
        if(sex.equals("Male"))
            return "Mr ";
        if(sex.equals("Female"))
            return "Miss ";
        else
            return "";
    }
    
    public static void setMax(){
        int max1=0,max2=0;
        for(int i = 0;i<8;i++){
            int sum=0;
            for(int j=0;j<7;j++){
                sum+=section[j].marks[i];
            }
            charTotal[i]=sum;
            if(sum>max1){
                max1=sum;
                char1=i;
            }
            else if(sum>max2){
                max2=sum;
                char2=i;
            }
        }
    }
    
//    public static String resultString(){
//        
//        String result = String.format("\n\t\t%-6s:%44s%-2s\n\t\t%-8s:%44s%-2s\n\t\t%-38s*%-9s\n\t\t%-56s*%-39s", "NAME","",userName,"SEX  ","",sex,
//                "Preferred self team role : ",(char1==-1?"":character[char1])," ",(char2==-1?"":character[char2]));
//        return result;
//    }
        
    
}

class Assessment{
 
    String[] questions = new String[8];
    int[] marks = new int[8];
    
    public Assessment(String... quest){
        setQuestions(quest);
    }
    public Assessment(){
        
    }
    
    public void setQuestions(String... quest){
        questions = quest;
    }
    
    public String[] getQuestions(){
        return questions;
    }
    
    public int[] getMarks(){
        return marks;
    }
    
    public void resetMarks(){
        marks = new int[8];
    }
    
    public int getTotalMarks(){
        int total=0;
        for(int x:marks)
            total+=x;
        return total;
    }
    
}